### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: com/chimbori/crux/articles/ArticleExtractor

### ISSUE THREAD

**Issue by Tony1952466760** [chimbori/crux#11]
Hi,I use crux version 2.0.1 or 2.0.2，when i build application and run it on command line 

`java -cp spider-text-extraction-0.1.0.jar com.persian.spider.App` 

Exception in thread "main" java.lang.NoClassDefFoundError: com/chimbori/crux/articles/ArticleExtractor                                 at com.persian.spider.SpiderArticle.textExtraction(SpiderArticle.java:20)                                                      at com.persian.spider.App.main(App.java:12)
Caused by: java.lang.ClassNotFoundException: com.chimbori.crux.articles.ArticleExtractor                                               at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)                                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 2 more

java version 
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

```

Can you help me? thank you.

**Comment by chimbori** [comment]
Your runtime environment is likely misconfigured, please check that Crux is correctly available on your classpath.
